version: '3.8' 
 
services: 
  rabbitmq: 
    image: rabbitmq:3.13-management 
    container_name: rabbitmq-broker 
    ports: 
      - "5672:5672"    # AMQP protocol port 
      - "15672:15672"  # Management UI port 
    environment: 
      RABBITMQ_DEFAULT_USER: guest 
      RABBITMQ_DEFAULT_PASS: guest 
    volumes: 
      - rabbitmq-data:/var/lib/rabbitmq 
    networks: 
      - rabbitmq-network 
 
volumes: 
  rabbitmq-data: 
 
networks: 
  rabbitmq-network: 
    driver: bridge 
